### ISSUE TITLE
issues with helm deployment

### ISSUE THREAD

**Issue by agoloAbbas** [tricksterproxy/trickster#352]
I faced an issue yesterday with Chart 1.1.2, it seems the 1.0-beta chaged to be copy of 1.0-beta10 which caused trickster to fail to start after updating my kubernetes cluster nodes and pulling the docker image. then I tried to update to latest chart.

for 1.3.0 also some values in values.yaml is duplicated like service section which cause an issue with config file having an empty listen_port

also PVC contains deprecated values for example https://github.com/Comcast/trickster/blob/6ac009f29aeeea9476da9db6311d0aa7cf39033c/deploy/helm/trickster/templates/pvc.yaml#L1 there is no section called config in current values.yaml

workaround: used tag 1.0.9-beta9

**Comment by jranson** [comment]
Thanks for this report. I will give this a quick look and update the helm chart and follow up shortly. Sorry for the issues!

**Comment by jranson** [comment]
@agoloAbbas these issue should be resolved in the latest release (Trickster 1.0.0-rc1, Chart 1.4.0). Please let use know if everything looks good for you now! Thank you again!

**Comment by agoloAbbas** [comment]
now it fails to pull 1.0.9-beta9
```
Failed to pull image "tricksterio/trickster:1.0-beta9": rpc error: code = Unknown desc = Error response from daemon: manifest for tricksterio/trickster:1.0-beta9 not found: manifest unknown: manifest unknown
```
why was this image deleted? I don't get it. It is so hard to keep using this solution

**Comment by nicopapayann** [comment]
Same problem here. Image deleted and now i have some issues with the chart. Could you reupload the image please?

**Comment by jranson** [comment]
@agoloAbbas Thanks for following up, and for sticking with the project during the beta process. I know that it required some effort to keep up as we released new versions, and we really appreciate it.

To your question about the image deletion: now that the 1.0 release is live, the beta images have been removed, so as to avoid users installing now-unsupported builds and filing issues against them. We only remove pre-release images, and only once they are obsolete, and never remove GA release images. For example, the previous GA release was `0.1.10` and that image will be available indefinitely. 

Would you mind checking that you synced the repository recently? The helm chart has been pointing to the `1.0` tag for about 6 days (see https://github.com/Comcast/trickster/blob/master/deploy/helm/trickster/values.yaml). That is a valid tag, so a quick sync of the repo should solve the tag issue you are experiencing.  `1.0` will be the primary image tag going forward, and will not be deleted.

We are in the process of getting the helm charts into their own repository so they can be added with a simple `helm repo add` which is being worked on #317

**Comment by jranson** [comment]
> Same problem here. Image deleted and now i have some issues with the chart. Could you reupload the image please?

Nico, can you please check your chart version? The image tag in the latest helm chart is `1.0`

**Comment by agoloAbbas** [comment]
simply I didn't migrate to it cuz I didn't find fixes for issues I reported for example right now. 
for example:-
ingress.enabled=true would fail the deployment

```
$helm diff upgrade -f values.yaml -f values-custom.yaml trickster --set ingress.enabled=true .
Error: render error in "trickster/templates/ingress.yaml": template: trickster/templates/ingress.yaml:4:27: executing "trickster/templates/ingress.yaml" at <.Values.trickster.service.servicePort>: nil pointer evaluating interface {}.service
render error in "trickster/templates/ingress.yaml": template: trickster/templates/ingress.yaml:4:27: executing "trickster/templates/ingress.yaml" at <.Values.trickster.service.servicePort>: nil pointer evaluating interface {}.service
Error: plugin "diff" exited with error```

it make no sense to delete old images while the current one is not working. or not stable enough to migrate to

**Comment by nicopapayann** [comment]
there are errors like @agoloAbbas  mentions, i try to patch the templates directory and still get more errors after, i agree with him deleting images without testing first.

**Comment by jranson** [comment]
Thanks for the additional information. We do test the charts with a `helm lint` and a `helm template`, which chart version `1.4.0` passed before it was released. I'm sorry to hear there are some errors despite those tests. Are there other validation tests that you can recommend we add? I am unfortunately just one person trying very hard to maintain this project and I am not a helm expert, so my apologies for the frustrations with this. I appreciate any constructive help to make this better.

**Comment by agoloAbbas** [comment]
I am willing to help you with helm but I would recommend to not deprecate 0.9 image as it would cause issue with anyone currently using the chart. 
I rebuilt the image localy and pushed to `agoloabdelsalam/trickster:v1.09-beta9` if anyone want to use it. I will create a pr soon to fix current deployment. 

I myself test helm with testing different scenarios y enabled different keys like ingress..etc to see if it will fail or not besides it seems the values.yaml file was alerted in way to that duplicated things. I will try to make a PR soon to fix it when I have time.

**Comment by jranson** [comment]
Thanks for the help! Is there an issue with the `1.0` image itself? I can run it in docker with no issues. It would be preferable to not use images of old beta software if the only issues are with the actual chart. I believe then that you should be able to take your working chart and update the image tag to `1.0` to have it work, while we work out the chart issues directly (irrespective of the image). If that does not work, can you provide the runtime error that the image returns when you try to run it?

**Comment by jranson** [comment]
@agoloAbbas and @nicopapayann it looks like removing the duplicate `service` section (which does not appear to be checked by `helm lint` and `helm template`) didn't quite make it into a PR, and that was my mistake - I was sure we'd taken care of it. We have a PR open to address that issue now.

Also, our gracious kube/helm reviewer (@LimitlessEarth) will be standing up a kube namespace in our test environment for verifying the end-to-end deployment of the chart. So he'll fix up any other issues, and integrate that environment into our standard verification steps. So hopefully we'll have any issues resolved in short order and will be able to catch them more reliably going forward. Thanks for your patience and all the great info!

BTW, the other issue with the chart you reported was the persistent volume claims, which we did address (and Adam will verify as per above and commit any additional fixes). PVC was incorrectly dependent upon a configuration value that only existed in the 0.1.x version of Trickster, and that is why it has been failing. With 1.0, you can configure multiple caches, and none, some, or all of those multiple caches could be a filesystem cache. It was not easy to migrate this logic (e.g., reading a scalar => iterator with a break). So instead, we now key off of the `.Values.persistentVolume.enabled` boolean to for PVC, which will need to be set to `true` for the claim to be made, irrespective of which caches are configured. We can certainly improve this to use a deterministic iterator that can break after making the claim, but `break` did not seem to be an intrinsic feature in helm templating. Again any help is welcomed!

**Comment by Abdelsalam-Abbas** [comment]
> 
> 
> Thanks for the help! Is there an issue with the `1.0` image itself? I can run it in docker with no issues. It would be preferable to not use images of old beta software if the only issues are with the actual chart. I believe then that you should be able to take your working chart and update the image tag to `1.0` to have it work, while we work out the chart issues directly (irrespective of the image). If that does not work, can you provide the runtime error that the image returns when you try to run it?

running old chart with new image would not work as it seems health probe endpoint has changed . so updating image tag within same chart is not a solution. pod keep restarting due to health probe failure.

**Comment by LimitlessEarth** [comment]
https://github.com/Comcast/trickster/pull/370
FYI

**Comment by nicopapayann** [comment]
thanks guys, i found a couple of problems and fixed them but there was one i really had trouble found a fix, i will wait for the merge.

**Comment by jranson** [comment]
Hi everyone, we have merged #370 into master, which is chart version 1.4.1. It is compatible with the 1.0 GA release and the release candidates, but will not work with the beta binaries prior to beta 10. Thanks for your patience while we got everything sorted out with the charts, and please let us know if there are any additional issues and we'll get them worked out as soon as possible.

**Comment by jranson** [comment]
All, closing this issue as there has been no more discussion since chart 1.4.1 was released. Note we have moved Trickster's Helm charts over to their own project at < https://github.com/tricksterproxy/helm-charts>, so please open any new issues discovered with the charts over there. The charts are now available as a chart repo, and you can find information about that at https://helm.tricksterproxy.io/ or on Helm Hub. The next main Trickster release will replace the deploy/helm directory with a notice of the charts relocation. Thanks again for this report and helping us get the charts in good shape!
